### ISSUE TITLE
Thanks your helpful program!🐱‍🏍

### ISSUE THREAD

**Issue by Fullstack-WEB-Blockchain-Developer** [dcarr178/har2openapi#5]
I'm using your code very helpful but what is meta?
Property meta is not allowed in Validation schema for OpenAPI Specification 3.0.X.
This is my code.
openapi: 3.0.0
info:
  title: LoopBack Application
  version: 1.0.0
paths:
  /autoServiceCategories:
    get:
      description: ''
      meta:
        element: ''
        originalPath: 'http://localhost:3001/api/autoServiceCategories'
      operationId: get-autoServiceCategories
      parameters: []
      responses: {}
      summary: 'List '
      tags:
        - AutoServiceCategories
    options:
      description: ''
     `meta`:
        element: ''
        originalPath: 'http://localhost:3001/api/autoServiceCategories'
      operationId: options-autoServiceCategories
      parameters: []
      responses: {}
      summary: SUMMARY
      tags:
        - AutoServiceCategories
    parameters: []

**Comment by dcarr178** [comment]
Meta is a temporary key that the program uses in an early stage to pass arguments to a later stage but then gets deleted before the final output.

**Comment by nmontmarquette** [comment]
Thanks for your tool! I'm reverse engineering some Website that isn't providing an API yet. Your tool got me started with Swagger, OAS3 :-)
